### ISSUE TITLE
Harmonize whitespaces

### ISSUE THREAD

**Issue by LucasVerneyDGE** [ambanum/CGUs#147]
https://github.com/ambanum/CGUs-versions/commit/3af7bf439 results in a notification when the only modifications happening are changes between non-breakable spaces and regular ones.

**Comment by MattiSG** [comment]
In the given example, there would have been a notification in any case, since [the last line changed](https://github.com/ambanum/CGUs-versions/commit/3af7bf439#diff-28600bbf50094536c29f48719962e1fdR446).

Let's see if there are other cases where space style results in noise :)

**Comment by MattiSG** [comment]
Closing as there has not been other instances of such noise for the moment. Feel free to reopen if it is spotted again! In any case, thanks for referencing this problem here, it allows to track the evolution of specific noise types 🙂

**Comment by clementbiron** [comment]
Spotted again [here](https://github.com/OpenTermsArchive/demo-versions/commit/868c3b2152654224d0f8cda7b5679a58589da90f).
