### ISSUE TITLE
[Reddit] Track the user agreement

### ISSUE THREAD

**Issue by LucasVerneyDGE** [ambanum/CGUs#153]
See https://www.redditinc.com/policies/user-agreement-october-15-2020 (FYI, I've been notified by email associated with my own account for the upcoming update).

**Comment by MattiSG** [comment]
It is apparently already tracked, as we just received an update for it: https://github.com/ambanum/CGUs-versions/commit/d21c1fdca 🙂

If I misunderstood the request, feel free to reopen the issue!

**Comment by LucasVerneyDGE** [comment]
Indeed, we can close this one.
