### ISSUE TITLE
Silent errors when request fails

### ISSUE THREAD

**Issue by LucasVerneyDGE** [ambanum/CGUs#165]
Hi,

When the request fails for some reason (in my particular case, a filtering proxy returning an unauthorized error), the error is silenced in the logs. See:

```
lverney@peren-app-jupyter:~/cgus$ npm start "Airbnb"

> cgus@0.0.1 start /home/lverney/cgus
> node src/index.js "Airbnb"

(node:2946) ExperimentalWarning: The ESM module loader is experimental.
2020-10-09 14:57:36 info                                                          Refiltering 3 documents from 1 services…
2020-10-09 14:57:36 info                                                          Refiltered 3 documents from 1 services.

2020-10-09 14:57:36 info                                                          Start tracking changes of 3 documents from 1 services…
2020-10-09 14:57:36 info                                                          Tracked changes of 3 documents from 1 services.
lverney@peren-app-jupyter:~/cgus$
```

(the "hint" to notice it is the absence of explicit "Recorded version" log, but it would probably be better to explicitly have a warning log on request returning anything else than a 200 HTTP code)

**Comment by LucasVerneyDGE** [comment]
@Ndpnt For some reason which I don't get, the `.error` handler on the queue is never called when an exception occurs: https://github.com/ambanum/CGUs/blob/master/src/app/index.js#L64-L65.

Using an error callback at the `push` level does work though, for example:
```
this._forEachDocumentOf(servicesIds, document => this.refilterDocumentsQueue.push(document, this.queueErrorHandler));
```

at the extra cost of moving `queueErrorHandler` as a class method and some extra tweaking to recover `serviceId` and `type`.

**Comment by Ndpnt** [comment]
Hi @LucasVerneyDGE,

Can you provide me an example, because I tried to throw an error in the `recorder` and the `errorHandler` is properly called for me.

**Comment by Ndpnt** [comment]
By the way, I was wondering, did you `npm install` last versions of dependencies because I had some issues with the previous version of the lib `async` and I guess it may come from this…

**Comment by LucasVerneyDGE** [comment]
> By the way, I was wondering, did you npm install last versions of dependencies because I had some issues with the previous version of the lib async and I guess it may come from this…

Removed the `node_modules` folder and `npm install` again to be sure. It is indeed working, thanks!
