### ISSUE TITLE
Déplacer l'historique dans un dépôt indépendant

### ISSUE THREAD

**Issue by Ndpnt** [ambanum/CGUs#19]
- [x] Transférer les fichiers dans un autre dépôt
- [x] Ajouter le dépôt de données comme sous-module du dépôt de code

Faut-il également séparer le dépôt des données brutes du dépôt des données nettoyées ?

**Comment by MattiSG** [comment]
Je me demande quelle est la valeur ajoutée du sous-module.
En particulier, je me demande ce qu'on attend de ce sous-module. Il ne peut clairement pas être toujours à jour (sinon autant qu'on garde la donnée dans ce dépôt-ci), donc à quelle occasion le met-on à jour ? Quel est l'intérêt d'un lien spécifique ? Est-ce qu'on considère que le commit pointé est le premier à partir duquel un certain mode de _sanitization_ est mis en place, par exemple ?
