### ISSUE TITLE
Add Proctorio

### ISSUE THREAD

**Issue by stuaxo** [ambanum/CGUs#194]
Hi,
   It would be good to add Proctorio.   They are an online exam company with certain interesting practices (e.g. telling people what they can/can not have in their rooms, enforced via a browser extension [1].

https://proctorio.com/terms
https://proctorio.com/privacy

They are also receiving some attention so their Ts and Cs may change.

[1] https://twitter.com/ejohnson99/status/1303142452233203714

**Comment by MattiSG** [comment]
Thanks @stuaxo! Do you feel like trying to declare this new service yourself? 😃 We'd be happy to get a pull request for it!

All the necessary documentation can be found in the [CONTRIBUTING](https://github.com/ambanum/CGUs/blob/master/CONTRIBUTING.md#tracking-new-documents) guide. You can also simply have a look at an [example service](https://github.com/ambanum/CGUs/blob/master/services/ASKfm.json) and try to duplicate it 🙂

Please let us know if you intend to try, and if there's anything we can help you with!

**Comment by stuaxo** [comment]
I'd like to, but I might not get a chance to for about a month or two, which is why I was a little cheeky and made the request here instead of actually doing the work.

Totally understand if noone else has time either :)
