### ISSUE TITLE
fetch error bubbles up to the top

### ISSUE THREAD

**Issue by michielbdejong** [ambanum/CGUs#203]
I tried `npm start` but after a couple of hours of good work, it suddenly exited:
```sh
2020-11-19 09:24:24 error Debka — Privacy Policy                                  FetchError: Invalid response body while trying to fetch https://www.debka.com/tac/: incorrect header check
    at Gunzip.<anonymous> (/home/tosback3/tosback-crawler/node_modules/node-fetch/lib/index.js:399:12)
    at Gunzip.emit (events.js:326:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

/home/tosback3/tosback-crawler/node_modules/async/dist/async.js:181
            setImmediate$1(e => { throw e }, err);
                                  ^
FetchError: Invalid response body while trying to fetch https://www.debka.com/tac/: incorrect header check
    at Gunzip.<anonymous> (/home/tosback3/tosback-crawler/node_modules/node-fetch/lib/index.js:399:12)
    at Gunzip.emit (events.js:326:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'Z_DATA_ERROR',
  code: 'Z_DATA_ERROR'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cgus@0.0.1 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cgus@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tosback3/.npm/_logs/2020-11-19T14_24_24_862Z-debug.log
```
That should never happen, right? It should just catch that error and continue with its next task?

**Comment by Ndpnt** [comment]
This behavior is expected. We only catch the error, log and continue with the next task when the error is an "expected error" (`404`, `500`, `ENOTFOUND`, `ETIMEDOUT`, `ECONNRESET`…). In this case we consider the error as an `InacessibleContentError`, but if the error is unknown and unexpected, like in your case `Z_DATA_ERROR` is not referenced as an `InacessibleContentError`, we stop the app immediately to avoid corrupting data.

**Comment by michielbdejong** [comment]
But this is an error in the gzipped data that was sent by the website right? So then the script will always crash when it reaches Debka? We can only ever fetch services A-D that way. I'll add a try-catch in our fork so that what happens at one service can never halt the whole script, let me know if you want a PR for it as well.

**Comment by MattiSG** [comment]
This is really by design. In the case you describe, we would fix or disable the failing service: we prefer to know that a specific service can not be tracked and should be fixed rather than have them all pass and maybe half being corrupt data. Are you sure you want to have silent failures in your fork? This is an important change, that we had thought of.

**Comment by michielbdejong** [comment]
OK, got it! Yes, in our case, contributors can specify document URLs and we need to be able to mark them as failing without crashing the process and then move on to the next document. We would not crawl failing documents every hour, but it's a natural state for our database to contain both correct and incorrect document descriptions.
