### ISSUE TITLE
Google extra terms of services

### ISSUE THREAD

**Issue by LVerneyPEReN** [ambanum/CGUs#223]
Hi,

Just to keep track, I found this page https://policies.google.com/terms/service-specific?hl=en-GB listing all the terms of services which are applicable for Google services as well as the extra terms of services for specific services. Might be worth double-checking we are tracking all of them.

Best,

**Comment by clementbiron** [comment]
A really interesting list, thank you ✔

We could prioritize the import of services using specific terms of services (like [Google drive](https://www.google.com/drive/terms-of-service/?hl=en_GB)). We will see this at the beginning of 2021.

**Comment by clementbiron** [comment]
We are working to add services on this branch https://github.com/ambanum/CGUs/tree/add-google-services.

**Comment by clementbiron** [comment]
Now merged in master branch 👍
