### ISSUE TITLE
Handling terms in PDF

### ISSUE THREAD

**Issue by LucasVerneyDGE** [ambanum/CGUs#52]
Hi,

While looking at app stores terms and developer policies, I came across the ones from Apple App Store, which are only available as PDF. See https://developer.apple.com/terms/apple-developer-agreement/Apple-Developer-Agreement-French.pdf.

Not sure how common this is and whether it might be worth developing ad-hoc code to handle PDF files?

I'm thinking of basically running `pdftotext` / `pdftohtml` from `popler-utils` or something more elaborate such as https://www.npmjs.com/package/pdf2html. This should be a bit carefully designed to integrate nicely in the current CD setup.

Best,

**Comment by MattiSG** [comment]
As discussed this morning with @LucasVerneyDGE and @Ndpnt: @LucasVerneyDGE will try to implement a PDF to HTML conversion and plug the result into the current pipeline 😃
For this first version, we can rely on the file extension in the URL to activate the PDF step in the pipeline. If this gets harder than expected, then we can introduce a `"filetype": "pdf"` property at the document level of service declarations.

If we end up having specific treatments based on file types, we might later autodetect MIME types of returned documents 🙂
