### ISSUE TITLE
Import history from tosback.org

### ISSUE THREAD

**Issue by MattiSG** [ambanum/CGUs#60]
As discussed this morning with @michielbdejong and @Ndpnt: import the history of snapshots from https://github.com/tosdr/tosback2/tree/master/crawl.

For each document of each service declaration present after #58:
- Get the oldest version in history from https://github.com/tosdr/tosback2/tree/master/crawl.
- Add a wrapper such as `<html><body>` to transform the HTML fragment into an HTML document parseable by JSdom.
- Store the text as a snapshot.
- Trigger filtering.
- Create a new version if appropriate.
- Ensure the date of the commit is the one of the original commit in TOSback, not the current date.
- Store reference to original commit in both snapshot and version commit messages, with a last line presenting a message such as `This snapshot was imported from
https://github.com/tosdr/tosback2/blob/5acac7abb5e967cfafd124a5e275f98f6ecd423e/crawl/4shared.com`.

## Open questions

- Should the date of the commit that reflects the TOSback one be the commit date or the author date? I'd prefer to use the author date as I believe it would keep the graph ordered by date, but @Ndpnt argues this might break GitHub's view. A check should be done on whether GitHub presents author date or commit date in history view.

**Comment by michielbdejong** [comment]
I'm thinking it makes sense to do this document-by-document. For instance
```sh
git log --pretty=format:"%h" --follow crawl_reviewed/google.com/Terms\ of\ Service.txt
81ba23f04
e9a2b2838
8e5823e42
[...]
```
Gives the history for Google's terms of service, which should be prepended to the history of `data/snapshots/Google/Terms\ of\ Service.html`.

**Comment by michielbdejong** [comment]
I'm working on this in https://github.com/ambanum/TOSBack-CGUs-bridge/issues/2

**Comment by michielbdejong** [comment]
Result from yesterday's run, using `git rebase --strategy-option=theirs`:
https://github.com/TosbackCgusBridge-Bot/CGUs-snapshots/tree/rebased-1602593779
https://github.com/TosbackCgusBridge-Bot/CGUs-versions/tree/rebased-1602593779

@Ndpnt please review?

**Comment by michielbdejong** [comment]
Ah I just noticed it creates a folder 'Deviantart' and one 'DeviantArt' next to each other. Will fix to comply with https://github.com/ambanum/CGUs/issues/106#issuecomment-681870747

**Comment by Ndpnt** [comment]
Thanks @michielbdejong.

For now:
- It seems Snapshot SHAs referred in Versions commits' messages are not valid. 
For example in the Version commit [`d79b8c6e90ef9fde90f7a5edc585d7c5745acd00`](https://github.com/TosbackCgusBridge-Bot/CGUs-versions/commit/d79b8c6e90ef9fde90f7a5edc585d7c5745acd00), it refers to the Snapshot commit [`885c6c80303209c8041e7620897c856c3081461d`](https://github.com/TosbackCgusBridge-Bot/CGUs-snapshots/commit/885c6c80303209c8041e7620897c856c3081461d) which seems unavailable.

- Each services have a commit with suspect `undefined` content like this one [`990b6aeac65dfe2b9c6f264016e9d2c1b2dcaefd`](https://github.com/TosbackCgusBridge-Bot/CGUs-versions/commit/990b6aeac65dfe2b9c6f264016e9d2c1b2dcaefd) or this one [`d79b8c6e90ef9fde90f7a5edc585d7c5745acd00`](https://github.com/TosbackCgusBridge-Bot/CGUs-versions/commit/d79b8c6e90ef9fde90f7a5edc585d7c5745acd00)

- There are `unknown` document types, for example [`2eeaa7ab856f8bd125f012532009e3ee1a70d23d`](https://github.com/TosbackCgusBridge-Bot/CGUs-versions/commit/2eeaa7ab856f8bd125f012532009e3ee1a70d23d)

- Commit messages don't follow CGUs-versions pattern. Ex: `Update Cableone/Terms of Service.html` should be `Update Cableone Terms of Service`

**Comment by Ndpnt** [comment]
- On Snapshots history there are commits with `undefined` content with message `Imported from undefined` like [`194d18113b58c73c8a495325cc0a5dc6a24af86c`](https://github.com/TosbackCgusBridge-Bot/CGUs-snapshots/commit/194d18113b58c73c8a495325cc0a5dc6a24af86c). This commit is also followed by a snapshot with empty content [`d3019c8d6a37fff0166721a80daff53d102e4b11`](https://github.com/TosbackCgusBridge-Bot/CGUs-snapshots/commit/d3019c8d6a37fff0166721a80daff53d102e4b11)

**Comment by michielbdejong** [comment]
Thanks, wow! All very useful. I'll fix these.

**Comment by michielbdejong** [comment]
Created 6 issues at https://github.com/ambanum/TOSBack-CGUs-bridge/issues.

**Comment by Ndpnt** [comment]
Just copy the comment in the PR #173, as it's more appropriate here:

> Also, for history importation:
> - Filenames and commits messages comply with service naming standards
> - Commits author date should match the original ToSback snapshot date
> - Import all snapshots from ToSBack, even when the types of documents are not currently supported in CGUs and even if documents do not pass validation. It will allow us to recover the history of theses documents when we will add these services and documents later.
> - Can you provide a list of services and documents for which the history could not be imported in the TOSBack-CGUs-bridge repository?

**Comment by michielbdejong** [comment]
> Filenames and commits messages comply with service naming standards

Yes, this is done in https://github.com/ambanum/TOSBack-CGUs-bridge/commit/e25205b71535fa7c83f2eff0e2600a0ef0b42ee1
Let me know if you still see any incorrect service names in the results of tonight's run, tomorrow.

> Commits author date should match the original ToSback snapshot date

Yes, for instance if I run `git log` on snapshots, I see:
```sh
commit b96c1693ab7ecc3f22c8f3230eadd859174b78a3 (HEAD -> import-1602755372)
Author: TOSBack CGUs bridge <tosback.cgus.bridge@unhosted.org>
Date:   Wed Jan 20 00:33:38 2016 -0500

    Update Cbsalary Privacy Policy
    
    Imported from https://github.com/tosdr/tosback2/blob/4e2c1ce814738e7375b075a8939cbec73e973e36/crawl/cbsalary.com/Privacy%20Policy.txt
    Snapshot originally obtained on 2016-01-20

commit 534b52590ac226a5a1f5dfd35ab84a7f3fa6c46e
Author: TOSBack CGUs bridge <tosback.cgus.bridge@unhosted.org>
Date:   Tue Jan 19 00:33:21 2016 -0500

    Update Cbsalary Privacy Policy
    
    Imported from https://github.com/tosdr/tosback2/blob/fcea0ed1b9c01aa597b9c9259628989fa70cd99f/crawl/cbsalary.com/Privacy%20Policy.txt
    Snapshot originally obtained on 2016-01-19

commit b4f8b098ff1c8bd369c28e8b8d1027c3c9c0f4bc
Author: TOSBack CGUs bridge <tosback.cgus.bridge@unhosted.org>
Date:   Mon Jan 18 00:31:47 2016 -0500

    Update Cbsalary Privacy Policy
    
    Imported from https://github.com/tosdr/tosback2/blob/9f43d5c90164e3a7b977647241a497957c3222e7/crawl/cbsalary.com/Privacy%20Policy.txt
    Snapshot originally obtained on 2016-01-18
```
Unfortunately the github web interface uses the committed date rather than the authored data, e.g.
https://github.com/TosbackCgusBridge-Bot/CGUs-snapshots/commits/import-1602593779
which is why we added the date inside the commit message as well.

> Import all snapshots from ToSBack, even when the types of documents are not currently supported in CGUs and even if documents do not pass validation. It will allow us to recover the history of theses documents when we will add these services and documents later.

Ah ok, so if the type is unknown you do not want the version and the rule, but you do want snapshot, correct? I had misunderstood that requirement then. I'll see if i have time to cancel the current run and change that tonight .

> Can you provide a list of services and documents for which the history could not be imported in the TOSBack-CGUs-bridge repository?

sure, i'll create a clear log of that.

**Comment by michielbdejong** [comment]
@Ndpnt done! See https://github.com/ambanum/TOSBack-CGUs-bridge/issues/20. Can you check the results and git reset your master branches to the rebased ones?

**Comment by MattiSG** [comment]
All of TosBack’s history has been imported at the CGUs format in https://github.com/ambanum/cgus-snapshots-tosback.

We decided not to merge it in https://github.com/ambanum/cgus-snapshots directly because we are still working on a way to rewrite the entire history at once with #156, and it will be much easier to rewrite everything once this is delivered.

Thanks again @michielbdejong! 🙂
